dist: trusty
language: ruby
rvm:
  - 2.4.3
sudo: required
addons:
  chrome: stable
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start