services:
  db:
    image: mysql:9.2.0
    environment:
      - MYSQL_DATABASE=orte
      - MYSQL_USER=orte
      - MYSQL_PASSWORD=orte00
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    image: a-thousand-channels/orte-backend:latest
    ports:
      - 127.0.0.1:3000:3000
    environment:
      RAILS_DB_HOST: db
      RAILS_DB_PASSWORD: orte00
      RAILS_SERVE_STATIC_FILES: true
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    depends_on:
      db:
        condition: service_healthy
