development:
  adapter: async

test:
  adapter: async

staging_async:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/
  channel_prefix: OrteBackend_staging

production:
  adapter: redis
  url: redis://localhost:6379/
  channel_prefix: OrteBackend_production

test:
  adapter: test