development:
  adapter: async

test:
  adapter: test

staging_async:
  adapter: async

staging:
  adapter: redis
  url: redis://localhost:6379/
  channel_prefix: OrteBackend_staging

production:
  adapter: redis
  url: redis://localhost:6379/
  channel_prefix: OrteBackend_production
  #  channel_prefix: orte_backend_production
