toolbar:
  - bold italic blockquote bullist code formatselect | link image | undo redo | fullscreen
plugins:
  - wordcount
  - image
  - link
  - lists
  - code
  - fullscreen
branding: false
menubar: false
statusbar: true